# Generated by Django 4.0.8 on 2022-12-07 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.aula'),
        ),
    ]
