# Generated by Django 4.1 on 2022-09-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', 'title'], 'verbose_name': 'horario', 'verbose_name_plural': 'horarios'},
        ),
    ]
