# Generated by Django 4.0.8 on 2022-11-23 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dia',
            table='pages_dia',
        ),
        migrations.AlterModelTable(
            name='disponibilidad',
            table='pages_disponibilidad',
        ),
        migrations.AlterModelTable(
            name='docentemateria',
            table='pages_docenteMateria',
        ),
        migrations.AlterModelTable(
            name='hora',
            table='pages_hora',
        ),
        migrations.AlterModelTable(
            name='page',
            table='pages_materia',
        ),
    ]
