# Generated by Django 4.0.7 on 2022-09-22 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_userdoce_useralum'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoceMate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preAca', models.CharField(max_length=250)),
                ('idDoce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.userdoce')),
                ('idMateria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.page')),
            ],
            options={
                'db_table': 'mate_doce',
            },
        ),
    ]
