# Generated by Django 4.0.7 on 2022-09-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['idMateria', 'nomMateria'], 'verbose_name': 'materia', 'verbose_name_plural': 'materias'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.RemoveField(
            model_name='page',
            name='id',
        ),
        migrations.RemoveField(
            model_name='page',
            name='order',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
        migrations.AddField(
            model_name='page',
            name='idMateria',
            field=models.CharField(default='0', max_length=10, primary_key=True, serialize=False, verbose_name='Clave de la materia'),
        ),
        migrations.AddField(
            model_name='page',
            name='nomMateria',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre de la materia'),
        ),
        migrations.AddField(
            model_name='page',
            name='numHoras',
            field=models.IntegerField(null=True, verbose_name='Numero de horas a la semana'),
        ),
        migrations.AlterModelTable(
            name='page',
            table='materia',
        ),
    ]
