# Generated by Django 4.0.8 on 2022-12-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_docentemateria_aula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='dia',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaldia',
            name='dia',
            field=models.CharField(db_index=True, max_length=45),
        ),
    ]
