# Generated by Django 4.0.8 on 2022-11-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_historicaldia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaldia',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical dia'},
        ),
        migrations.AlterModelOptions(
            name='historicaldisponibilidad',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical disponibilidad'},
        ),
        migrations.AlterModelOptions(
            name='historicaldocentemateria',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical docente materia'},
        ),
        migrations.AlterModelOptions(
            name='historicalhora',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical hora'},
        ),
        migrations.AlterModelOptions(
            name='historicalpage',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical page'},
        ),
        migrations.AlterField(
            model_name='historicaldia',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicaldisponibilidad',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicaldocentemateria',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalhora',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalpage',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
