# Generated by Django 4.0.7 on 2022-09-26 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userNom', models.CharField(max_length=50, verbose_name='Nombre')),
                ('userApepat', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('userApemat', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=registration.models.custom_upload_to)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='UserDoce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRol', models.CharField(choices=[('C', 'Coordinacion'), ('M', 'Maestro'), ('A', 'Alumno')], default='M', max_length=1)),
                ('idDoce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.profile')),
            ],
            options={
                'db_table': 'docente',
            },
        ),
        migrations.CreateModel(
            name='UserCor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRol', models.CharField(choices=[('C', 'Coordinacion'), ('M', 'Maestro'), ('A', 'Alumno')], default='M', max_length=1)),
                ('idCor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.profile')),
            ],
            options={
                'db_table': 'coordinador',
            },
        ),
        migrations.CreateModel(
            name='UserAlum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRol', models.CharField(choices=[('C', 'Coordinacion'), ('M', 'Maestro'), ('A', 'Alumno')], default='A', max_length=1)),
                ('idAlum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.profile')),
            ],
            options={
                'db_table': 'alumno',
            },
        ),
    ]
