# Generated by Django 4.0.7 on 2022-09-22 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDoce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRol', models.CharField(choices=[('C', 'Coordinacion'), ('M', 'Maestro'), ('A', 'Alumno')], default='M', max_length=1)),
                ('numHoras', models.IntegerField(verbose_name='Numero de horas a la semana')),
                ('idDoce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.profile')),
            ],
            options={
                'db_table': 'docentes',
            },
        ),
        migrations.CreateModel(
            name='UserAlum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRol', models.CharField(choices=[('C', 'Coordinacion'), ('M', 'Maestro'), ('A', 'Alumno')], default='A', max_length=1)),
                ('idAlum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.profile')),
            ],
            options={
                'db_table': 'alumnos',
            },
        ),
    ]
