# Generated by Django 4.0.7 on 2022-09-22 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_userdoce_useralum'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useralum',
            table='alumno',
        ),
        migrations.AlterModelTable(
            name='userdoce',
            table='docente',
        ),
        migrations.CreateModel(
            name='UserCor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRol', models.CharField(choices=[('C', 'Coordinacion'), ('M', 'Maestro'), ('A', 'Alumno')], default='M', max_length=1)),
                ('idCor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.profile')),
            ],
            options={
                'db_table': 'coordinador',
            },
        ),
    ]
