# Generated by Django 4.0.7 on 2022-10-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_profile_pic',
            field=models.ImageField(blank=True, upload_to='usuarios/admin_profile_pic'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='alumno_profile_pic',
            field=models.ImageField(blank=True, upload_to='usuarios/alumno_profile_pic'),
        ),
        migrations.AlterField(
            model_name='coordina',
            name='coordina_profile_pic',
            field=models.ImageField(blank=True, upload_to='usuarios/cordina_profile_pic'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='docente_profile_pic',
            field=models.ImageField(blank=True, upload_to='usuarios/docente_profile_pic'),
        ),
        migrations.AlterModelTable(
            name='admin',
            table='administrador',
        ),
        migrations.AlterModelTable(
            name='alumno',
            table='alumno',
        ),
        migrations.AlterModelTable(
            name='coordina',
            table='coordinador',
        ),
        migrations.AlterModelTable(
            name='docente',
            table='docente',
        ),
        migrations.AlterModelTable(
            name='user',
            table='usuario',
        ),
    ]
