# Generated by Django 4.0.8 on 2022-12-02 14:11

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_profile_pic',
            field=models.ImageField(blank=True, upload_to=usuarios.models.custom_admin_upload_to),
        ),
        migrations.AlterField(
            model_name='coordina',
            name='coordina_profile_pic',
            field=models.ImageField(blank=True, upload_to=usuarios.models.custom_coordina_upload_to),
        ),
        migrations.AlterField(
            model_name='docente',
            name='docente_profile_pic',
            field=models.ImageField(blank=True, upload_to=usuarios.models.custom_docente_upload_to),
        ),
    ]
