# Generated by Django 4.0.7 on 2022-10-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_user_options_alter_admin_admin_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='user_administrador',
        ),
        migrations.AlterModelTable(
            name='alumno',
            table='user_alumno',
        ),
        migrations.AlterModelTable(
            name='coordina',
            table='user_coordinador',
        ),
        migrations.AlterModelTable(
            name='docente',
            table='user_docente',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user_usuario',
        ),
    ]
