# Generated by Django 4.1 on 2022-09-04 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_useralum_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useralum',
            options={'ordering': ['idU', 'created'], 'verbose_name': 'alumno', 'verbose_name_plural': 'alumnos'},
        ),
    ]
