# Generated by Django 4.0.7 on 2022-10-24 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_admin_table_alter_alumno_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
    ]
