# Generated by Django 4.1 on 2022-09-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_userdoce'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdoce',
            options={'ordering': ['idU', 'created'], 'verbose_name': 'docente', 'verbose_name_plural': 'docentes'},
        ),
    ]
