# Generated by Django 4.0.7 on 2022-10-24 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_admin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordina',
            options={'permissions': [('add_page', 'Can add page')]},
        ),
    ]
