# Generated by Django 4.0.7 on 2022-10-24 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_coordina_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordina',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
    ]
