# Generated by Django 4.0.7 on 2022-10-24 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_coordina_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'default_permissions': ('change', 'view')},
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
    ]
