# Generated by Django 4.0.8 on 2022-11-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_historicaldocente_historicalcoordina_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalalumno',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical alumno', 'verbose_name_plural': 'historical alumnos'},
        ),
        migrations.AlterModelOptions(
            name='historicalcoordina',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical coordina', 'verbose_name_plural': 'historical coordinas'},
        ),
        migrations.AlterModelOptions(
            name='historicaldocente',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical docente', 'verbose_name_plural': 'historical docentes'},
        ),
        migrations.AlterField(
            model_name='historicalalumno',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcoordina',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaldocente',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.DeleteModel(
            name='HistoricalAdmin',
        ),
    ]
