# Generated by Django 4.0.8 on 2022-11-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_historicalalumno_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalalumno',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical alumno'},
        ),
        migrations.AlterModelOptions(
            name='historicalcoordina',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical coordina'},
        ),
        migrations.AlterModelOptions(
            name='historicaldocente',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical docente'},
        ),
        migrations.AlterField(
            model_name='historicalalumno',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalcoordina',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicaldocente',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
