# Generated by Django 4.0.7 on 2022-09-26 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'plantel',
            },
        ),
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claveLicenci', models.CharField(max_length=10)),
                ('nomLicenci', models.CharField(max_length=50)),
                ('calendario', models.CharField(max_length=5)),
                ('plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.institucion')),
            ],
            options={
                'db_table': 'licenciatura',
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claveAula', models.CharField(max_length=10)),
                ('grupo', models.CharField(max_length=1)),
                ('licenciatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.licenciatura')),
            ],
            options={
                'db_table': 'aula',
            },
        ),
    ]
