# Generated by Django 4.0.8 on 2022-11-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantel',
            name='plantel',
            field=models.CharField(max_length=100),
        ),
    ]
