# Generated by Django 4.0.8 on 2022-11-23 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aula',
            table='institucion_aula',
        ),
        migrations.AlterModelTable(
            name='licenciatura',
            table='institucion_licenciatura',
        ),
        migrations.AlterModelTable(
            name='plantel',
            table='institucion_plantel',
        ),
        migrations.AlterModelTable(
            name='semestre',
            table='institucion_semestre',
        ),
    ]
