# Generated by Django 4.0.7 on 2022-09-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='grupo',
            field=models.CharField(max_length=1),
        ),
    ]
