# Generated by Django 4.0.8 on 2022-10-26 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciatura',
            name='plantel',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='institucion.plantel'),
        ),
    ]
