# Generated by Django 4.0.8 on 2022-12-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_alter_aula_table_alter_licenciatura_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='clave',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalaula',
            name='clave',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicallicenciatura',
            name='clave',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalplantel',
            name='clave',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='clave',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='plantel',
            name='clave',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
