# Generated by Django 4.0.8 on 2022-11-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_alter_plantel_plantel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantel',
            name='plantel',
            field=models.CharField(max_length=200),
        ),
    ]
